FROM node:19.7.0 AS builder
ENV NODE_ENV=production
WORKDIR /app
COPY ["package.json", "package-lock.json*", "./"]
RUN npm install
COPY . .
CMD [ "npm", "run", "build"]

FROM nginx
#RUN rm /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build/. /usr/share/nginx/html
#COPY conf /etc/nginx